AWSTemplateFormatVersion: '2010-09-09'
Description: s3 resource
Parameters:
  ServiceName:
    Type: String
    Default: cfn-sample
  EnvSuffix:
    Type: String
    Default: -dev
    AllowedValues:
      - -dev
      - -qa
      - ''

Resources:
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/ecs/${ServiceName}${EnvSuffix}
      RetentionInDays: 14
      Tags:
        - Key: "CfnStackName"
          Value: !Ref AWS::StackName
  
  FireLensLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/ecs/${ServiceName}-firelens${EnvSuffix}
      RetentionInDays: 14
      Tags:
        - Key: "CfnStackName"
          Value: !Ref AWS::StackName

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '', [ !Ref ServiceName, -logs, !Ref EnvSuffix ] ]
      VersioningConfiguration:
        Status: Suspended
      LifecycleConfiguration:
        Rules:
          - Id: !Join [ '', [ !Ref ServiceName, -tweet-logs-lifecycle-policy, !Ref EnvSuffix ] ]
            Prefix: fluent-bit-logs/tweet-log/
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: "CfnStackName"
          Value: !Ref AWS::StackName