name: code build
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build image
    env:
      SERVICE_NAME: cfn-sample-dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache App Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-app
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Cache LogRouter Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-log
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc-cfn-sample-dev
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - uses: docker/build-push-action@v2
      id: build-app-image
      with:
        push: true
        file: deploy/development/Dockerfile
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache-app
        cache-to: type=local,dest=/tmp/.buildx-cache-app-new,mode=max
    
    - uses: docker/build-push-action@v2
      id: build-firelens-image
      with:
        push: true
        file: deploy/development/firelens/Dockerfile
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:log-router
        cache-from: type=local,src=/tmp/.buildx-cache-log
        cache-to: type=local,dest=/tmp/.buildx-cache-log-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache-app
        mv /tmp/.buildx-cache-app-new /tmp/.buildx-cache-app
        rm -rf /tmp/.buildx-cache-log
        mv /tmp/.buildx-cache-log-new /tmp/.buildx-cache-log