name: code test
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/myapp_test
      DATABASE_PASSWORD: postgres
      DATABASE_USERNAME: postgres
      RAILS_ENV: test
      BUNDLE_PATH: vendor/bundle
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install dependencies
        run: bundle install
      - name: db setup
        run: bundle exec rake db:migrate
      - name: Run tests
        run: bundle exec rake test